ProjeYonetim/ProjeYonetim/Controllers/KullaniciController.cs
using ProjeYonetim.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeYonetim.Controllers
{

    public class KullaniciController : Controller
    {
        Service.AppService service = new Service.AppService();
        [HttpGet]
        public ActionResult Liste()
        {
            return View(service.KullaniciListele());
        }

        [HttpGet]
        public ActionResult Yeni()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Yeni(Kullanicilar kullanici)
        {
            var durum = service.KullaniciEkle(kullanici);
            if (durum)
                return RedirectToAction("Liste");

            return View();
        }

        [HttpGet]
        public ActionResult Duzenle(int Id)
        {
            return View(service.KullaniciGetir(Id));
        }
        [HttpPost]
        public ActionResult Duzenle(int Id, Kullanicilar kullanici)
        {
            var durum = service.KullaniciGuncelle(kullanici);
            if (durum)
                return RedirectToAction("Liste");

            return View();
        }

        [HttpPost]
        public JsonResult Sil(int Id)
        {
            var result = Core.ProjeRepository.KullaniciSil(Id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

    }
}

ProjeYonetim/ProjeYonetim/Views/Kullanici/Duzenle.cshtml
@model ProjeYonetim.Models.Kullanicilar
@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">@Model.KullaniciAdi | Duzenleniyor</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Duzenle", "Kullanici", FormMethod.Post))
                            {
                                @Html.HiddenFor(model=>model.ID)
                                <div class="form-group">
                                    <label>Kullanıcı Adı</label>
                                    @Html.TextBoxFor(model => model.KullaniciAdi, new { @class = "form-control", @required = "required" })
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @required = "required" })
                                </div>
                                <div class="form-group">
                                    <label>Şifre</label>
                                    @Html.TextBoxFor(model => model.Sifre, new { @class = "form-control", @required = "required" })
                                </div>
                                <div class="pull-right">
                                    <a href="/Kullanici/Liste" class="btn btn-default">Listele</a>
                                    <button type="submit" class="btn btn-default">Kaydet</button>

                                </div>
                            }
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->

ProjeYonetim/ProjeYonetim/Views/Kullanici/Liste.cshtml
@model List<ProjeYonetim.Models.Kullanicilar>
@{
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}
@section Styles{
    <!-- DataTables CSS -->
    <link href="~/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet" />
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet" />
}
<!-- Navigation -->

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">KULLANICI LİSTESİ</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                   
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Kullanıcı Adı</th>
                                <th>Email</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                string rowStyle = "odd gradeX";
                                int i = 0;
                                foreach (var item in Model)
                                {
                                    if (i % 2 == 0)
                                    {
                                        rowStyle = "even gradeC";
                                    }
                                    else
                                    {
                                        rowStyle = "odd gradeX";
                                    }
                                    <tr class="@rowStyle">
                                        <td>@item.KullaniciAdi</td>
                                        <td>@item.Email</td>
                                        <td>
                                            <a href="/Kullanici/Duzenle/@item.ID"><i class="fa fa-edit">Düzenle</i></a>
                                            <button onclick="Sil(@item.ID)"><i class="fa fa-remove"></i>Sil</button>
                                        </td>
                                    </tr>
                                    i++;
                                }
                            }
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /#page-wrapper -->

@section Scripts{
    <!-- DataTables JavaScript -->
    <script src="~/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Content/js/sb-admin-2.min.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>

    <script type="text/javascript">
        function Sil(ID) {
            if (confirm("Seçtiğiniz Kayıtı silmek istediğinize emin misiniz ?")) {
                var post = { Id: ID }
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Sil", "Kullanici")',
                    dataType: 'json',
                    data: post,
                    success: function (result) {
                        if (result) {
                            location.reload();
                        }
                        else {
                            alert("Silmek istediğiniz kayıt ile ilgili veriler mevcut silinemez!");
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                       alert("İşlem Hatası")
                    }
                });
            }
        }
    </script>
}

ProjeYonetim/ProjeYonetim/Views/Kullanici/Yeni.cshtml
@model ProjeYonetim.Models.Kullanicilar
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Yeni Kullanıcı</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-body">
                    <div class="row">
                        <div class="col-lg-12">
                            @using (Html.BeginForm("Yeni", "Kullanici", FormMethod.Post))
                            {
                                <div class="form-group">
                                    <label>Kullanıcı Adı</label>
                                    @Html.TextBoxFor(model => model.KullaniciAdi, new { @class = "form-control", @required = "required" })
                                </div>
                                <div class="form-group">
                                    <label>Email</label>
                                    @Html.TextBoxFor(model => model.Email, new { @class = "form-control", @required = "required" })
                                </div>
                                <div class="form-group">
                                    <label>Şifre</label>
                                    @Html.TextBoxFor(model => model.Sifre, new { @class = "form-control", @required = "required" })
                                </div>
                                <div class="pull-right">
                                    <a href="/Kullanici/Liste" class="btn btn-default">Listele</a>
                                    <button type="submit" class="btn btn-default">Kaydet</button>
                                </div>
                            }
                        </div>
                    </div>
                    <!-- /.row (nested) -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
</div>
<!-- /#page-wrapper -->