ProjeYonetim/ProjeYonetim/Controllers/ProjeController.cs
using ProjeYonetim.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeYonetim.Controllers
{
    public class ProjeController : Controller
    {
        Service.AppService service = new Service.AppService();
        [HttpGet]
        public ActionResult Liste()
        {
            return View(service.ProjeListele());
        }

        [HttpGet]
        public ActionResult Yeni()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Yeni(Projeler proje)
        {
            var durum = service.ProjeEkle(proje);
            if (durum)
                return RedirectToAction("Liste");

            return View();
        }

        [HttpGet]
        public ActionResult Duzenle(int Id)
        {
            return View(service.ProjeGetir(Id));
        }
        [HttpPost]
        public ActionResult Duzenle(int Id, Projeler proje)
        {
            var durum = service.ProjeGuncelle(proje);
            if (durum)
                return RedirectToAction("Liste");

            return View();
        }

        [HttpPost]
        public JsonResult Sil(int Id)
        {
            var result = Core.ProjeRepository.ProjeSil(Id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }


    }
}

ProjeYonetim/ProjeYonetim/Views/Proje/Duzenle.cshtml
@model ProjeYonetim.Models.Projeler
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}

    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">@Model.ProjeAdi | Düzenleme</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                @using (Html.BeginForm("Duzenle", "Proje", FormMethod.Post))
                                {
                                    @Html.HiddenFor(model => model.ID)
                                    <div class="form-group">
                                        <label>Proje Adı</label>
                                        @Html.TextBoxFor(model => model.ProjeAdi, new { @class = "form-control", @required = "required" })
                                    </div>
                                    <div class="form-group">
                                        <label>Proje Durumu</label>
                                        @Html.DropDownListFor(m => m.DurumId, new SelectList(ProjeYonetim.Core.ProjeRepository.GetProjeDurumList(), "ID", "DurumAdi"), "Seçiniz..", new { @class = "form-control", @required = "required" })
                                    </div>
                                    <div class="form-group">
                                        <label>Açıklama</label>
                                        @Html.TextAreaFor(model => model.Aciklama, new { @class = "form-control", @required = "required" })
                                    </div>
                                    <div class="form-group">
                                        <label>Başlangıç Tarihi</label>
                                        @Html.TextBoxFor(model => model.BaslangicTarihi, new { @class = "form-control", @required = "required", @value = Model.BaslangicTarihi })
                                    </div>
                                    <div class="form-group">
                                        <label>Bitiş Tarihi</label>
                                        @Html.TextBoxFor(model => model.BitisTarihi, new { @class = "form-control", @required = "required", @value = Model.BitisTarihi })
                                    </div>
                                    <div class="form-group">
                                        <label>Görevli Kullanıcı</label>
                                        @Html.DropDownListFor(m => m.KullaniciId, new SelectList(ProjeYonetim.Core.ProjeRepository.GetProjeKullaniciList(), "ID", "KullaniciAdi"), "Seçiniz..", new { @class = "form-control", @required = "required" })

                                    </div>
                                    <div class="pull-right">
                                        <a href="/Proje/Liste" class="btn btn-default">Listele</a>
                                        <button type="submit" class="btn btn-default">Kaydet</button>

                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>

ProjeYonetim/ProjeYonetim/Views/Proje/Liste.cshtml
@model List<ProjeYonetim.Models.VW_Projeler>
@{
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}
@section Styles{
    <!-- DataTables CSS -->
    <link href="~/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet" />
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet" />
}
<!-- Navigation -->

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">PROJE LİSTESİ</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">

                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Proje Adı</th>
                                <th>Durum</th>
                                <th>Kullanıcı</th>
                                <th>Başlangıç Tarihi</th>
                                <th>Bitiş Tarihi</th>

                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                string rowStyle = "odd gradeX";
                                int i = 0;
                                foreach (var item in Model)
                                {
                                    if (i % 2 == 0)
                                    {
                                        rowStyle = "even gradeC";
                                    }
                                    else
                                    {
                                        rowStyle = "odd gradeX";
                                    }
                                    <tr id="row_@item.PROJE_ID" class="@rowStyle">
                                        <td>@item.ProjeAdi</td>
                                        <td>@item.DurumAdi</td>
                                        <td>@item.KullaniciAdi</td>
                                        <td>@Convert.ToDateTime(item.BaslangicTarihi).ToShortDateString()</td>
                                        <td>@Convert.ToDateTime(item.BitisTarihi).ToShortDateString()</td>
                                        <td>
                                            <a href="/Proje/Duzenle/@item.PROJE_ID">Düzenle</a>
                                            <button onclick="Sil(@item.PROJE_ID)"><i class="fa fa-remove"></i>Sil</button>
                                        </td>
                                    </tr>
                                    i++;
                                }
                            }
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /#page-wrapper -->

@section Scripts{
    <!-- DataTables JavaScript -->
    <script src="~/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Content/js/sb-admin-2.min.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->

    <script type="text/javascript">
        function Sil(ID) {
            if (confirm("Seçtiğiniz Kayıtı silmek istediğinize emin misiniz ?")) {
                var post = { Id: ID }
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Sil", "Proje")',
                    dataType: 'json',
                    data: post,
                    success: function (result) {
                        if (result) {
                            location.reload();
                        }
                        else {
                            alert("Silme başarısız");
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                       alert("İşlem Hatası")
                    }
                });
            }
        }
    </script>
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>


}

ProjeYonetim/ProjeYonetim/Views/Proje/Yeni.cshtml
@model ProjeYonetim.Models.Projeler
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}

    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Yeni Proje</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                @using (Html.BeginForm("Yeni", "Proje", FormMethod.Post))
                                {
                                    <div class="form-group">
                                        <label>Proje Adı</label>
                                        @Html.TextBoxFor(model => model.ProjeAdi, new { @class = "form-control",@required="required" })
                                    </div>
                                    <div class="form-group">
                                        <label>Proje Durumu</label>
                                        @Html.DropDownListFor(m => m.DurumId, new SelectList(ProjeYonetim.Core.ProjeRepository.GetProjeDurumList(), "ID", "DurumAdi"), "Seçiniz..", new { @class = "form-control", @required = "required" })
                                    </div>
                                    <div class="form-group">
                                        <label>Açıklama</label>
                                        @Html.TextAreaFor(model => model.Aciklama, new { @class = "form-control", @required = "required" })
                                    </div>
                                    <div class="form-group">
                                        <label>Başlangıç Tarihi</label>
                                        @Html.TextBoxFor(model => model.BaslangicTarihi, new { @class = "form-control", @type = "date", @required = "required" })
                                    </div>
                                    <div class="form-group">
                                        <label>Bitiş Tarihi</label>
                                        @Html.TextBoxFor(model => model.BitisTarihi, new { @class = "form-control", @type = "date", @required = "required" })
                                    </div>
                                    <div class="form-group">
                                        <label>Görevli Kullanıcı</label>
                                        @Html.DropDownListFor(m => m.KullaniciId, new SelectList(ProjeYonetim.Core.ProjeRepository.GetProjeKullaniciList(), "ID", "KullaniciAdi"), "Seçiniz..", new { @class = "form-control", @required = "required" })

                                    </div>
                                    <div class="pull-right">
                                        <a href="/Proje/Liste" class="btn btn-default">Listele</a>
                                        <button type="submit" class="btn btn-default">Kaydet</button>

                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->