ProjeYonetim/ProjeYonetim/Controllers/ProjeDurumController.cs
using ProjeYonetim.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjeYonetim.Controllers
{
    public class ProjeDurumController : Controller
    {

        Service.AppService service = new Service.AppService();
        [HttpGet]
        public ActionResult Liste()
        {
            return View(service.ProjeDurumlariListele());
        }

        [HttpGet]
        public ActionResult Yeni()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Yeni(ProjeDurumlari projeDurum)
        {
            var durum = service.ProjeDurumEkle(projeDurum);
            if (durum)
                return RedirectToAction("Liste");

            return View();
        }

        [HttpGet]
        public ActionResult Duzenle(int Id)
        {
            return View(service.ProjeDurumGetir(Id));
        }
        [HttpPost]
        public ActionResult Duzenle(int Id, ProjeDurumlari projeDurum)
        {
            var durum = service.ProjeDurumGuncelle(projeDurum);
            if (durum)
                return RedirectToAction("Liste");

            return View();
        }

        [HttpPost]
        public JsonResult Sil(int Id)
        {
            var result = Core.ProjeRepository.ProjeDurumSil(Id);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
    }
}

ProjeYonetim/ProjeYonetim/Views/ProjeDurum/Duzenle.cshtml
@model ProjeYonetim.Models.ProjeDurumlari
@{
    ViewBag.Title = "Duzenle";
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}

    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">@Model.DurumAdi | Düzenleniyor</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                @using (Html.BeginForm("Duzenle", "ProjeDurum", FormMethod.Post))
                                {
                                    @Html.HiddenFor(model => model.ID)
                                    <div class="form-group">
                                        <label>Durum Adı</label>
                                        @Html.TextBoxFor(model => model.DurumAdi, new { @class = "form-control", @required = "required" })
                                    </div>

                                    <div class="pull-right">
                                        <a href="/ProjeDurum/Liste" class="btn btn-default">Listele</a>
                                        <button type="submit" class="btn btn-default">Kaydet</button>
                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>

ProjeYonetim/ProjeYonetim/Views/ProjeDurum/Liste.cshtml
@model List<ProjeYonetim.Models.ProjeDurumlari>
@{
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}
@section Styles{
    <!-- DataTables CSS -->
    <link href="~/Content/vendor/datatables-plugins/dataTables.bootstrap.css" rel="stylesheet" />
    <!-- DataTables Responsive CSS -->
    <link href="~/Content/vendor/datatables-responsive/dataTables.responsive.css" rel="stylesheet" />
}
<!-- Navigation -->

<div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">PROJE DURUM LİSTESİ</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                  
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
                        <thead>
                            <tr>
                                <th>Durum</th>
                                <th>İşlem</th>
                            </tr>
                        </thead>
                        <tbody>
                            @{
                                string rowStyle = "odd gradeX";
                                int i = 0;
                                foreach (var item in Model)
                                {
                                    if (i % 2 == 0)
                                    {
                                        rowStyle = "even gradeC";
                                    }
                                    else
                                    {
                                        rowStyle = "odd gradeX";
                                    }
                                    <tr class="@rowStyle">
                                        <td>@item.DurumAdi</td>
                                        <td>
                                            <a href="/ProjeDurum/Duzenle/@item.ID">Düzenle</a>
                                            <button onclick="Sil(@item.ID)"><i class="fa fa-remove"></i>Sil</button>
                                        </td>
                                    </tr>
                                    i++;
                                }
                            }
                        </tbody>
                    </table>
                    <!-- /.table-responsive -->
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
        <!-- /.col-lg-12 -->
    </div>
</div>
<!-- /#page-wrapper -->

@section Scripts{
    <!-- DataTables JavaScript -->
    <script src="~/Content/vendor/datatables/js/jquery.dataTables.min.js"></script>
    <script src="~/Content/vendor/datatables-plugins/dataTables.bootstrap.min.js"></script>
    <script src="~/Content/vendor/datatables-responsive/dataTables.responsive.js"></script>
    <!-- Custom Theme JavaScript -->
    <script src="~/Content/js/sb-admin-2.min.js"></script>
    <!-- Page-Level Demo Scripts - Tables - Use for reference -->
    <script>
        $(document).ready(function () {
            $('#dataTables-example').DataTable({
                responsive: true
            });
        });
    </script>
    <script type="text/javascript">
        function Sil(ID) {
            if (confirm("Seçtiğiniz Kayıtı silmek istediğinize emin misiniz ?")) {
                var post = { Id: ID }
                $.ajax({
                    type: 'POST',
                    url: '@Url.Action("Sil", "ProjeDurum")',
                    dataType: 'json',
                    data: post,
                    success: function (result) {
                        if (result) {
                            location.reload();
                        }
                        else {
                            alert("Silme başarısız");
                        }
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                       alert("İşlem Hatası")
                    }
                });
            }
        }
    </script>
}

ProjeYonetim/ProjeYonetim/Views/ProjeDurum/Yeni.cshtml
@model ProjeYonetim.Models.ProjeDurumlari
@{
    ViewBag.Title = "Yeni";
    Layout = "~/Views/Shared/adminLayoutPage.cshtml";
}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Yeni Proje Durumu</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12">
                                @using (Html.BeginForm("Yeni", "ProjeDurum", FormMethod.Post))
                                {
                                    <div class="form-group">
                                        <label>Durum Adı</label>
                                        @Html.TextBoxFor(model => model.DurumAdi, new { @class = "form-control", @required = "required" })
                                    </div>
                                   
                                    <div class="pull-right">
                                        <a href="/ProjeDurum/Liste" class="btn btn-default">Listele</a>
                                        <button type="submit" class="btn btn-default">Kaydet</button>
                                    </div>
                                }
                            </div>
                        </div>
                        <!-- /.row (nested) -->
                    </div>
                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->